export const BLUETOOTH_STATUS = 'BLUETOOTH_STATUS';
export const BLUETOOTH_ERROR = 'BLUETOOTH_ERROR';
export const BLUETOOTH_SCANING = 'BLUETOOTH_SCANING';
export const SET_BLUETOOTH_UNPAIRED = 'SET_BLUETOOTH_UNPAIRED';
export const SET_BLUETOOTH_PAIRED = 'SET_BLUETOOTH_PAIRED';
export const BLUETOOTH_CONNECTING = 'BLUETOOTH_CONNECTING';
export const BLUETOOTH_CONNECTED = 'BLUETOOTH_CONNECTED';

export const COMPASS_STATUS = 'COMPASS_STATUS';
export const SET_COMPASS = 'SET_COMPASS';


export const GPS_STATUS = 'GPS_STATUS';
export const SET_GPS = 'SET_GPS';
export const SET_GPS_WATCHER = 'SET_WATCHER';
export const SET_GPS_AVAILABLE = 'SET_GPS_AVAILABLE';


export const SERVER_STATUS = 'SERVER_STATUS';
export const SERVER_AUTH = 'SERVER_AUTH';


export const CAR_ENGINE_STATUS = 'CAR_ENGINE_STATUS';
export const CAR_LISTEN = 'CAR_LISTEN';
export const CAR_ENGINE_LOAD = 'CAR_ENGINE_LOAD';
export const CAR_ENGINE_RPM = 'CAR_ENGINE_RPM';
export const CAR_SPEED = 'CAR_SPEED';
export const CAR_COOLANT = 'CAR_COOLANT';